### ISSUE TITLE
ARM template create qna maker resource instance in wrong region

### ISSUE THREAD

**Issue by Mikhail2k15** [OfficeDev/microsoft-teams-apps-faqplus#128]
![image](https://user-images.githubusercontent.com/11201670/127106533-b2ccb34d-887c-449d-b427-825941e1a5ba.png)

**Comment by shsarda** [comment]
The location of QnA maker in ARM template is hardcoded to "westus".
I tried changing the region/location of the qna maker resource in ARM template to one of the locations mentioned in this doc - Azure Products by Region | Microsoft Azure
For example, I changed the location to "eastus"
It gives an error in deployment - 
![image](https://user-images.githubusercontent.com/63221418/132221255-33386484-b8b9-474a-909a-4940df1177d4.png)


I tried creating a QnA maker resource in "eastus" in the Azure portal -

![image](https://user-images.githubusercontent.com/63221418/132221237-cbb23084-fd04-4193-93cc-091783b31835.png)

But the actual resource is created in "westus" by default. Export template of the same resource looks like -
![image](https://user-images.githubusercontent.com/63221418/132221385-c1e8579f-dce5-4454-a736-3f14e35bf061.png)

QnA maker cerates resource in "westus" by default in the portal.
So, only "westus" is supported for this resource by design.
