### ISSUE TITLE
Getting Error "There was a problem reaching this app"

### ISSUE THREAD

**Issue by shanemeisner** [OfficeDev/microsoft-teams-apps-faqplus#141]
When opening the App in Teams I get "There was a problem reaching this app" : 
![image](https://user-images.githubusercontent.com/67586976/134666974-77193ca2-4421-4bac-82dc-a6545051ede2.png)

Even though I see that error, the bot is working and responding.
 The interesting thing is not everyone sees that error. Test with 10 people and only myself and one other person saw that message. 

Also, if I click on Apps and select to open the App from the list of apps, the error goes away for that time. 
But if I try clicking the App again from the navigation bar, the error comes back.
If I go to Teams in a Web Browser the error does not show.

I have tried uninstalling the app from my client and re-adding, same issue. 
Deleted all cache files from Teams, same issue.
Restarted the services in Azure - same issue.

Any idea how to resolve this?

**Comment by ahmedmahmoudR** [comment]
@shanemeisner  are you solved the issue ?

**Comment by ahmedmahmoudR** [comment]
@v-smahaj  any advice pls

**Comment by emiludev** [comment]
Hi, we have the same issue here, is there any update to solve this?

**Comment by shanemeisner** [comment]
@SubbaReddi any thoughts?

**Comment by shanemeisner** [comment]
@Mikhail2k15 Can you review?

**Comment by SubbaReddi** [comment]
@shanemeisner: This is Global issue in Desktop Teams, not related to specific application.  And the fix rollout is in progress. You can see the same in Service health:
![image](https://user-images.githubusercontent.com/69682598/136689367-8855670c-7cda-461b-a379-64f889ae707e.png)

Work around solution before fix roll out:
Works fine in Web teams 
And access bot from "Chat" instead of opening bot from applications.
Hope it helps?
