### ISSUE TITLE
Ask an expert option is not working

### ISSUE THREAD

**Issue by mahybabu** [OfficeDev/microsoft-teams-apps-faqplus#15]
I followed the deployment guide as is,
https://github.com/OfficeDev/microsoft-teams-apps-faqplusv2/wiki/Deployment-Guide

But, When I click on ask an expert from the bot application, its throwing an error 'Unable to reach app. Please try again.' though I have configured the app with the right Teams ID.

**Comment by prithvi7410** [comment]
Is the app running now or you are still facing the issue ?

**Comment by jimcollierGF** [comment]
I'm have the very same issue.  Anytime I hit ask an expert, I get a response "something went wrong".  Here is a screenshot of what I get back. 
<img width="567" alt="Screen Shot 2020-09-11 at 12 32 13 AM" src="https://user-images.githubusercontent.com/30299592/92860601-6f9f3380-f3c6-11ea-8bd4-14a4eb6852f9.png">

**Comment by hunterspark** [comment]
Think you'll find the issue is that you're using the faqplus-expert template for the app in Teams - in the instructions you followed there were 2 templates created, if you install the other (faqplus-enduser) this works as expected! Did exactly the same thing myself, probably assumes that if you're running the expert version you are one and would therefore not need to ask a question. Hope this helps.

**Comment by v-smahaj** [comment]
Let us know if the issue still persists.

**Comment by cmack00** [comment]
I have the same issue. The only thing I can think of is that I changed the ID field in the manifest because I already have another version of FAQ plus being used in our org for another department and maybe the ID is coded somewhere???
