### ISSUE TITLE
Multi-turn is not working.

### ISSUE THREAD

**Issue by emiludev** [OfficeDev/microsoft-teams-apps-faqplus#178]
Hello, we have installed the latest version of FaqPlus in our Azure Tenant, and we observe that the multi-turn option does not work properly, clicking on any of the options of the question with multi-turn returns the answer "I didn' t find a matching answer for this question. Do you want me to ask an expert?"

This functionality worked correctly in the previous version.

Here are screenshots.

![FaqPlus-001](https://user-images.githubusercontent.com/79489808/182959129-21213203-f63d-4bb0-9e07-d5246f895430.png)

![FaqPlus-002](https://user-images.githubusercontent.com/79489808/182959341-7b8361cd-e84f-49a3-adaa-e55930af9db5.png)

Is there any way to solve this?

Thanks.

**Comment by v-royavinash** [comment]
@emiludev The work around for multi turn options is, user can type the available shown options instead of selecting the options and the bot will responds to the user.

If you think this work around will not be considered for the users, you can use the previous version of the app which is available in the below location, however this is something which we don’t normally recommend to users.

[OfficeDev/microsoft-teams-apps-faqplus at v2.1 (github.com)](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FOfficeDev%2Fmicrosoft-teams-apps-faqplus%2Ftree%2Fv2.1&data=05%7C01%7Cv-royavinash%40microsoft.com%7C84db3501722240b6f94e08da5dab3c9f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637925287335152830%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=gO1%2BU5a1MpRdmK6h%2F3FjPTgD05xGbEj4JByj%2BkdFpws%3D&reserved=0)
