### ISSUE TITLE
FAQPlus tips for reducing the subscription costs whilst developing and testing.

### ISSUE THREAD

**Issue by westerdaled** [OfficeDev/microsoft-teams-apps-faqplus#46]
If anyone has sucessfully deploy the FAQPlus bot esp. in the UK, I wonder what sort of accumlating costs you are now  seeing .   hopefully not looking like a the costs of  associated with a gambling or drug addiction 🤨!  If not I am keen to explore what you have configured in terms of managing the costs. 

![FAQPlus costs](https://user-images.githubusercontent.com/937208/89399003-c2236b00-d709-11ea-860f-77447c1e05bc.PNG)

I have started looking at the offending services

- FAQApp Service: I am currently using the S1 service plan as I cannot use the F1 ( free ) or any of the target compute plans because of the "Always on" service .  Is there a way to get around this such write a script to disable / reenable  unitl needed?

- Search service - Pricing Tier basic : 1 repica, 1 partition ,1 search unit. Again, is there a way to enable / disable until needed?

- FAQApp Congnative Servies :  F0 Free

**Comment by jjbol123** [comment]
Good afternoon Daniel, despite all the help, including yours, I have not yet managed to get the MS FAQ Plus App working. See my message. But if I understand you correctly, the costs quickly add up. I agree with you that it would be more cost-effective to disable certain functionalities. And only switch on again when you really need them. Thanks for investigating the costs, by the way.

**Comment by westerdaled** [comment]
Hi @jjbol123 I have responded to your message. You could try one of the other samples such as the [Communicator ](https://github.com/OfficeDev/microsoft-teams-company-communicator-app) as away of validating your environment. 

To reduce costs  I have configured the following

1. - Set Bot App service configuration:  <code>Always On </code> to Off
2. - Set Bot-config App service configuration:  <code>Always On </code> to Off
3. - Set Bot-function  ( azure function) configuration:  <code>Always On </code> to Off
4. - Set Bot App service plan : To (F1 free)

**Comment by abbodh** [comment]
Hi @westerdaled , you can try to reduce the app service plan SKU further to Basic if looking for cost considerations. This can be done from azure portal directly to scale down the SKU for Standard to Basic plan. Please note that the app service plan is hosting 3 web apps i.e. bot app service, config app service and azure function. 

I wouldn't recommend to turn off either of the services, because the cost is associated to service plan and not specific app service inside service plan and you will be billed as long as app service exists.  

Note - this should be done just for testing and demo purpose and if you are running it as a production service then please monitor the services and enable auto-scale as per need.

**Comment by westerdaled** [comment]
@abbodh  thanks for your reply. Just to clarify your recommendation, I have switched the App Service Plan to F1  from S1 .  I have also set the Azure Search Service pricing tier  to Basic. Is this what your are referring to?

You have highlighted the main issue here.  When we go through the deployment steps, we immediately start hitting charges,  just for the resources  existing. This is not great for development.  It is ironic, given my bot is deployed to MS Teams, hosted in a free dev tenant.  MS aren't yet testing me for each team that exists😣!  There must be a way to stand up all the resources for a bot in a resource group: test , then export / archive the current version of the resources.  We then later restore the archived version when needed either in dev or for live with an appropriate app service plan.

**Comment by westerdaled** [comment]
I have now located the biggest drain on my wallet aka the Azure Search service ( this most be hosted in a sold gold data center!)  Has anyone found a way to amend the pricing tier from Basic to the  Free ? Hopefully I don't do this via a new resource group?

**Comment by Hickey77** [comment]
Here's mine at ~$107USD/Mo 
Web App Bot: F0 plan (free)
Cognitive Services:  F0 plan (free)
Application Insights: 3 Instances - 90 day retention ($2.37/mo)
App Service Plan: B1 – can’t go lower due to AlwaysOn requirement ($35.52)
App Service:  Included with App Service Plan (free)
Config App Service:  Included with App Service Plan (free)
Function App: Included with App Service Plan (free)
QnaMaker App: Included with App Service Plan (free)
Storage Account: LRS ($.58)
Search Service: 1 Replica ($74.13)

**Comment by westerdaled** [comment]
Hmmm that is not insignificant.  I spoke to the Azure Search Services  team and found my issue is that I could only have one free plan per environment . So it is really my responsibility to create -> Test  -> backup -> delete , before testing out the next bot or whatever, that requires Azure Search services ( as this is the main culprit ) .
