### ISSUE TITLE
Disable ask the expert

### ISSUE THREAD

**Issue by arichards-Hable** [OfficeDev/microsoft-teams-apps-faqplus#88]
Hi. Not an issue more a query. Is it possible to turn off the option for the Ask the Expert and Send Feedback options

**Comment by cagrimunyas** [comment]
Hello,
Yes, it's quite possible. I'm currently handling a similar request for my customer. You can simply remove the related actions from the adaptive card models and also remove the statement that handles the ask and expert and share feedback card commands in the bot onMessageActivityAsync method.

**Comment by SrivatsanVasudevan** [comment]
Hi,

Yes, it's possible to remove the ask an expert and share feedback options by making the required code changes to remove the buttons from the adaptive card and deploying the bot using the forked copy where you made the changes. You will also have to remove references of the two buttons from the manifest file and make the appropriate string changes in the resources files to avoid any references to the two buttons and their functionalities. You will also need to ensure that when you type ask an expert or share feedback in Teams, that the bot shouldn't return adaptive cards regarding these two options. Also, since there will not be an ask an expert team, we can delete the manifest_sme.json file and also get rid of the Team ID text field to be filled in, in step 5 of the deployment process.

I've created a new branch with these changes, https://github.com/SrivatsanVasudevan/microsoft-teams-apps-faqplus/tree/srivatsan/disableAskAnExpert. Deploying the bot from this forked copy and branch should deploy the bot without the ask an expert and share feedback options.
